---
driver_plugin: vagrant
driver_config:
  # see https://github.com/test-kitchen/test-kitchen/issues/440
  require_chef_omnibus: 11.14.0.rc.2 -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
- name: ubuntu-12.04
  driver_config:
    box: chef/ubuntu-12.04-i386

suites:
- name: default
  run_list: ["recipe[sample-app]"]
  attributes: {}
