---
driver_plugin: vagrant
driver_config:
  # see https://github.com/test-kitchen/test-kitchen/issues/440
  require_chef_omnibus: 11.16.4 -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
- name: ubuntu-12.04-i386
  driver_config:
    box: chef/ubuntu-12.04-i386
    customize:
      memory: 256


suites:
- name: default
  run_list: ["recipe[sample-app]"]
  attributes: {}
