version: '{build}-{branch}'
os: Windows Server 2012
platform:
  - x64
init:
- ps: |
    mkdir C:\Users\appveyor\.vagrant.d | Out-Null
    echo @'
    Vagrant::configure('2') do |config|
      config.vm.boot_timeout = 1020
    end
    '@ | Out-File -encoding UTF8 C:\Users\appveyor\.vagrant.d\Vagrantfile
- ps: |
    mkdir C:\downloads | Out-Null
    cd C:\downloads
    Start-FileDownload "https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.1.msi"
    Start-Process -FilePath "msiexec.exe" -ArgumentList "/a vagrant_1.7.1.msi /qb TARGETDIR=C:\Vagrant-1.7.1" -Wait
    Start-FileDownload "http://download.virtualbox.org/virtualbox/4.3.20/VirtualBox-4.3.20-96997-Win.exe"
    Start-Process -FilePath "VirtualBox-4.3.20-96997-Win.exe" -ArgumentList "-silent -logging -msiparams INSTALLDIR=C:\VBox-4.3.20" -Wait
    Start-FileDownload 'https://gist.githubusercontent.com/tknerr/71fc51b591db47541a46/raw/cacert.pem'
    cd $env:APPVEYOR_BUILD_FOLDER
- ps: |
    While ((Test-NetConnection google.com -Port 80 -InformationLevel Quiet) -ne "True") {
        echo "waiting for network..."
        Start-Sleep 1
    }
cache:
- C:\Ruby200\lib\ruby\gems\2.0.0
- C:\Ruby200\bin
install:
- set PATH=C:\Vagrant-1.7.1\HashiCorp\Vagrant\bin;C:\Ruby200\bin;C:\VBox-4.3.20;%PATH%
- set SSL_CERT_FILE=C:\downloads\cacert.pem
- vagrant -v
- VBoxManage -v
- ruby --version
- gem --version
- gem install bundler --quiet --no-ri --no-rdoc
- bundler --version
build_script:
- bundle install
test_script:
- rake spec
